platform :ios, '8.0'
pod 'SDWebImage', '~>3.8'
pod 'MBProgressHUD', '~> 1.0.0'
pod 'ZFPlayer'
pod 'YYKit'
pod 'MJExtension'
pod 'Masonry'
pod 'FMDB'
pod 'BmobSDK'
pod 'EaseMobSDKFull', '~>2.2.7'
pod 'BaiduMapKit'
pod 'MJRefresh'
pod 'SVProgressHUD'
pod 'AFNetworking', '~> 2.6.2'
pod "MWPhotoBrowser"
pod 'Pgyer'
pod 'PgyUpdate'
pod "DACircularProgress"
target 'XQQChatProj' do

end
