platform :ios, '8.0'
pod 'SDWebImage', '~>3.8'
pod 'ZFPlayer', '~> 2.0.0'
pod 'YYKit'
pod 'MJExtension'
pod 'Masonry'
pod 'FMDB'
pod 'BmobSDK'

pod 'BaiduMapKit'
pod 'MJRefresh'
pod 'MBProgressHUD', '~> 1.0.0'
pod 'SVProgressHUD'
pod 'AFNetworking', '~> 2.6.2'
pod "DACircularProgress"
target 'XQQChatProj' do
pod 'MSWeakTimer', '~> 1.1.0'
pod 'EaseMobSDKFull', :git => 'https://github.com/easemob/sdk-ios-cocoapods-integration.git'
pod "MWPhotoBrowser"
end
